// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

private func doubleEqualsNuxieBridge(_ lhs: Double, _ rhs: Double) -> Bool {
  return (lhs.isNaN && rhs.isNaN) || lhs == rhs
}

private func doubleHashNuxieBridge(_ value: Double, _ hasher: inout Hasher) {
  if value.isNaN {
    hasher.combine(0x7FF8000000000000)
  } else {
    // Normalize -0.0 to 0.0
    hasher.combine(value == 0 ? 0 : value)
  }
}

func deepEqualsNuxieBridge(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
    return true

  case is (Void, Void):
    return true

  case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !deepEqualsNuxieBridge(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsArray, let rhsArray) as ([Double], [Double]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !doubleEqualsNuxieBridge(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard lhsDictionary.count == rhsDictionary.count else { return false }
    for (lhsKey, lhsValue) in lhsDictionary {
      var found = false
      for (rhsKey, rhsValue) in rhsDictionary {
        if deepEqualsNuxieBridge(lhsKey, rhsKey) {
          if deepEqualsNuxieBridge(lhsValue, rhsValue) {
            found = true
            break
          } else {
            return false
          }
        }
      }
      if !found { return false }
    }
    return true

  case (let lhs as Double, let rhs as Double):
    return doubleEqualsNuxieBridge(lhs, rhs)

  case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
    return lhsHashable == rhsHashable

  default:
    return false
  }
}

func deepHashNuxieBridge(value: Any?, hasher: inout Hasher) {
  let cleanValue = nilOrValue(value) as Any?
  if let cleanValue = cleanValue {
    if let doubleValue = cleanValue as? Double {
      doubleHashNuxieBridge(doubleValue, &hasher)
    } else if let valueList = cleanValue as? [Any?] {
      for item in valueList {
        deepHashNuxieBridge(value: item, hasher: &hasher)
      }
    } else if let valueList = cleanValue as? [Double] {
      for item in valueList {
        doubleHashNuxieBridge(item, &hasher)
      }
    } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
      var result = 0
      for (key, value) in valueDict {
        var entryKeyHasher = Hasher()
        deepHashNuxieBridge(value: key, hasher: &entryKeyHasher)
        var entryValueHasher = Hasher()
        deepHashNuxieBridge(value: value, hasher: &entryValueHasher)
        result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
      }
      hasher.combine(result)
    } else if let hashableValue = cleanValue as? AnyHashable {
      hasher.combine(hashableValue)
    } else {
      hasher.combine(String(describing: cleanValue))
    }
  } else {
    hasher.combine(0)
  }
}


/// Generated class from Pigeon that represents data sent in messages.
struct PConfigureRequest: Hashable {
  var session: String? = nil
  var apiKey: String? = nil
  var wrapperVersion: String? = nil
  var usingPurchaseController: Bool? = nil
  var environment: String? = nil
  var logLevel: String? = nil
  var localeIdentifier: String? = nil
  var purchaseHandlingMode: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PConfigureRequest? {
    let session: String? = nilOrValue(pigeonVar_list[0])
    let apiKey: String? = nilOrValue(pigeonVar_list[1])
    let wrapperVersion: String? = nilOrValue(pigeonVar_list[2])
    let usingPurchaseController: Bool? = nilOrValue(pigeonVar_list[3])
    let environment: String? = nilOrValue(pigeonVar_list[4])
    let logLevel: String? = nilOrValue(pigeonVar_list[5])
    let localeIdentifier: String? = nilOrValue(pigeonVar_list[6])
    let purchaseHandlingMode: String? = nilOrValue(pigeonVar_list[7])

    return PConfigureRequest(
      session: session,
      apiKey: apiKey,
      wrapperVersion: wrapperVersion,
      usingPurchaseController: usingPurchaseController,
      environment: environment,
      logLevel: logLevel,
      localeIdentifier: localeIdentifier,
      purchaseHandlingMode: purchaseHandlingMode
    )
  }
  func toList() -> [Any?] {
    return [
      session,
      apiKey,
      wrapperVersion,
      usingPurchaseController,
      environment,
      logLevel,
      localeIdentifier,
      purchaseHandlingMode,
    ]
  }
  static func == (lhs: PConfigureRequest, rhs: PConfigureRequest) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsNuxieBridge(lhs.session, rhs.session) && deepEqualsNuxieBridge(lhs.apiKey, rhs.apiKey) && deepEqualsNuxieBridge(lhs.wrapperVersion, rhs.wrapperVersion) && deepEqualsNuxieBridge(lhs.usingPurchaseController, rhs.usingPurchaseController) && deepEqualsNuxieBridge(lhs.environment, rhs.environment) && deepEqualsNuxieBridge(lhs.logLevel, rhs.logLevel) && deepEqualsNuxieBridge(lhs.localeIdentifier, rhs.localeIdentifier) && deepEqualsNuxieBridge(lhs.purchaseHandlingMode, rhs.purchaseHandlingMode)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PConfigureRequest")
    deepHashNuxieBridge(value: session, hasher: &hasher)
    deepHashNuxieBridge(value: apiKey, hasher: &hasher)
    deepHashNuxieBridge(value: wrapperVersion, hasher: &hasher)
    deepHashNuxieBridge(value: usingPurchaseController, hasher: &hasher)
    deepHashNuxieBridge(value: environment, hasher: &hasher)
    deepHashNuxieBridge(value: logLevel, hasher: &hasher)
    deepHashNuxieBridge(value: localeIdentifier, hasher: &hasher)
    deepHashNuxieBridge(value: purchaseHandlingMode, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PFeatureAccess: Hashable {
  var allowed: Bool? = nil
  var unlimited: Bool? = nil
  var balance: Double? = nil
  var type: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PFeatureAccess? {
    let allowed: Bool? = nilOrValue(pigeonVar_list[0])
    let unlimited: Bool? = nilOrValue(pigeonVar_list[1])
    let balance: Double? = nilOrValue(pigeonVar_list[2])
    let type: String? = nilOrValue(pigeonVar_list[3])

    return PFeatureAccess(
      allowed: allowed,
      unlimited: unlimited,
      balance: balance,
      type: type
    )
  }
  func toList() -> [Any?] {
    return [
      allowed,
      unlimited,
      balance,
      type,
    ]
  }
  static func == (lhs: PFeatureAccess, rhs: PFeatureAccess) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsNuxieBridge(lhs.allowed, rhs.allowed) && deepEqualsNuxieBridge(lhs.unlimited, rhs.unlimited) && deepEqualsNuxieBridge(lhs.balance, rhs.balance) && deepEqualsNuxieBridge(lhs.type, rhs.type)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PFeatureAccess")
    deepHashNuxieBridge(value: allowed, hasher: &hasher)
    deepHashNuxieBridge(value: unlimited, hasher: &hasher)
    deepHashNuxieBridge(value: balance, hasher: &hasher)
    deepHashNuxieBridge(value: type, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PFeatureUsageResult: Hashable {
  var success: Bool? = nil
  var featureId: String? = nil
  var amountUsed: Double? = nil
  var message: String? = nil
  var usageCurrent: Double? = nil
  var usageLimit: Double? = nil
  var usageRemaining: Double? = nil
  var authoritativeAccess: PFeatureAccess? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PFeatureUsageResult? {
    let success: Bool? = nilOrValue(pigeonVar_list[0])
    let featureId: String? = nilOrValue(pigeonVar_list[1])
    let amountUsed: Double? = nilOrValue(pigeonVar_list[2])
    let message: String? = nilOrValue(pigeonVar_list[3])
    let usageCurrent: Double? = nilOrValue(pigeonVar_list[4])
    let usageLimit: Double? = nilOrValue(pigeonVar_list[5])
    let usageRemaining: Double? = nilOrValue(pigeonVar_list[6])
    let authoritativeAccess: PFeatureAccess? = nilOrValue(pigeonVar_list[7])

    return PFeatureUsageResult(
      success: success,
      featureId: featureId,
      amountUsed: amountUsed,
      message: message,
      usageCurrent: usageCurrent,
      usageLimit: usageLimit,
      usageRemaining: usageRemaining,
      authoritativeAccess: authoritativeAccess
    )
  }
  func toList() -> [Any?] {
    return [
      success,
      featureId,
      amountUsed,
      message,
      usageCurrent,
      usageLimit,
      usageRemaining,
      authoritativeAccess,
    ]
  }
  static func == (lhs: PFeatureUsageResult, rhs: PFeatureUsageResult) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsNuxieBridge(lhs.success, rhs.success) && deepEqualsNuxieBridge(lhs.featureId, rhs.featureId) && deepEqualsNuxieBridge(lhs.amountUsed, rhs.amountUsed) && deepEqualsNuxieBridge(lhs.message, rhs.message) && deepEqualsNuxieBridge(lhs.usageCurrent, rhs.usageCurrent) && deepEqualsNuxieBridge(lhs.usageLimit, rhs.usageLimit) && deepEqualsNuxieBridge(lhs.usageRemaining, rhs.usageRemaining) && deepEqualsNuxieBridge(lhs.authoritativeAccess, rhs.authoritativeAccess)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PFeatureUsageResult")
    deepHashNuxieBridge(value: success, hasher: &hasher)
    deepHashNuxieBridge(value: featureId, hasher: &hasher)
    deepHashNuxieBridge(value: amountUsed, hasher: &hasher)
    deepHashNuxieBridge(value: message, hasher: &hasher)
    deepHashNuxieBridge(value: usageCurrent, hasher: &hasher)
    deepHashNuxieBridge(value: usageLimit, hasher: &hasher)
    deepHashNuxieBridge(value: usageRemaining, hasher: &hasher)
    deepHashNuxieBridge(value: authoritativeAccess, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PFeatureSnapshot: Hashable {
  var session: String? = nil
  var identityGeneration: Int64? = nil
  var revision: Int64? = nil
  var state: String? = nil
  var all: [String?: PFeatureAccess?]? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PFeatureSnapshot? {
    let session: String? = nilOrValue(pigeonVar_list[0])
    let identityGeneration: Int64? = nilOrValue(pigeonVar_list[1])
    let revision: Int64? = nilOrValue(pigeonVar_list[2])
    let state: String? = nilOrValue(pigeonVar_list[3])
    let all: [String?: PFeatureAccess?]? = nilOrValue(pigeonVar_list[4])

    return PFeatureSnapshot(
      session: session,
      identityGeneration: identityGeneration,
      revision: revision,
      state: state,
      all: all
    )
  }
  func toList() -> [Any?] {
    return [
      session,
      identityGeneration,
      revision,
      state,
      all,
    ]
  }
  static func == (lhs: PFeatureSnapshot, rhs: PFeatureSnapshot) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsNuxieBridge(lhs.session, rhs.session) && deepEqualsNuxieBridge(lhs.identityGeneration, rhs.identityGeneration) && deepEqualsNuxieBridge(lhs.revision, rhs.revision) && deepEqualsNuxieBridge(lhs.state, rhs.state) && deepEqualsNuxieBridge(lhs.all, rhs.all)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PFeatureSnapshot")
    deepHashNuxieBridge(value: session, hasher: &hasher)
    deepHashNuxieBridge(value: identityGeneration, hasher: &hasher)
    deepHashNuxieBridge(value: revision, hasher: &hasher)
    deepHashNuxieBridge(value: state, hasher: &hasher)
    deepHashNuxieBridge(value: all, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PVersions: Hashable {
  var nativeVersion: String? = nil
  var contract: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PVersions? {
    let nativeVersion: String? = nilOrValue(pigeonVar_list[0])
    let contract: Int64? = nilOrValue(pigeonVar_list[1])

    return PVersions(
      nativeVersion: nativeVersion,
      contract: contract
    )
  }
  func toList() -> [Any?] {
    return [
      nativeVersion,
      contract,
    ]
  }
  static func == (lhs: PVersions, rhs: PVersions) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsNuxieBridge(lhs.nativeVersion, rhs.nativeVersion) && deepEqualsNuxieBridge(lhs.contract, rhs.contract)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PVersions")
    deepHashNuxieBridge(value: nativeVersion, hasher: &hasher)
    deepHashNuxieBridge(value: contract, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PExperienceRef: Hashable {
  var experienceId: String? = nil
  var experienceVersion: String? = nil
  var journeyId: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PExperienceRef? {
    let experienceId: String? = nilOrValue(pigeonVar_list[0])
    let experienceVersion: String? = nilOrValue(pigeonVar_list[1])
    let journeyId: String? = nilOrValue(pigeonVar_list[2])

    return PExperienceRef(
      experienceId: experienceId,
      experienceVersion: experienceVersion,
      journeyId: journeyId
    )
  }
  func toList() -> [Any?] {
    return [
      experienceId,
      experienceVersion,
      journeyId,
    ]
  }
  static func == (lhs: PExperienceRef, rhs: PExperienceRef) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsNuxieBridge(lhs.experienceId, rhs.experienceId) && deepEqualsNuxieBridge(lhs.experienceVersion, rhs.experienceVersion) && deepEqualsNuxieBridge(lhs.journeyId, rhs.journeyId)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PExperienceRef")
    deepHashNuxieBridge(value: experienceId, hasher: &hasher)
    deepHashNuxieBridge(value: experienceVersion, hasher: &hasher)
    deepHashNuxieBridge(value: journeyId, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PAppAction: Hashable {
  var name: String? = nil
  var payload: [String?: Any?]? = nil
  var experience: PExperienceRef? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PAppAction? {
    let name: String? = nilOrValue(pigeonVar_list[0])
    let payload: [String?: Any?]? = nilOrValue(pigeonVar_list[1])
    let experience: PExperienceRef? = nilOrValue(pigeonVar_list[2])

    return PAppAction(
      name: name,
      payload: payload,
      experience: experience
    )
  }
  func toList() -> [Any?] {
    return [
      name,
      payload,
      experience,
    ]
  }
  static func == (lhs: PAppAction, rhs: PAppAction) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsNuxieBridge(lhs.name, rhs.name) && deepEqualsNuxieBridge(lhs.payload, rhs.payload) && deepEqualsNuxieBridge(lhs.experience, rhs.experience)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PAppAction")
    deepHashNuxieBridge(value: name, hasher: &hasher)
    deepHashNuxieBridge(value: payload, hasher: &hasher)
    deepHashNuxieBridge(value: experience, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PActivityInfo: Hashable {
  var schemaVersion: Int64? = nil
  var id: String? = nil
  var timestampMs: Int64? = nil
  var receivedAtMs: Int64? = nil
  var name: String? = nil
  var properties: [String?: Any?]? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PActivityInfo? {
    let schemaVersion: Int64? = nilOrValue(pigeonVar_list[0])
    let id: String? = nilOrValue(pigeonVar_list[1])
    let timestampMs: Int64? = nilOrValue(pigeonVar_list[2])
    let receivedAtMs: Int64? = nilOrValue(pigeonVar_list[3])
    let name: String? = nilOrValue(pigeonVar_list[4])
    let properties: [String?: Any?]? = nilOrValue(pigeonVar_list[5])

    return PActivityInfo(
      schemaVersion: schemaVersion,
      id: id,
      timestampMs: timestampMs,
      receivedAtMs: receivedAtMs,
      name: name,
      properties: properties
    )
  }
  func toList() -> [Any?] {
    return [
      schemaVersion,
      id,
      timestampMs,
      receivedAtMs,
      name,
      properties,
    ]
  }
  static func == (lhs: PActivityInfo, rhs: PActivityInfo) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsNuxieBridge(lhs.schemaVersion, rhs.schemaVersion) && deepEqualsNuxieBridge(lhs.id, rhs.id) && deepEqualsNuxieBridge(lhs.timestampMs, rhs.timestampMs) && deepEqualsNuxieBridge(lhs.receivedAtMs, rhs.receivedAtMs) && deepEqualsNuxieBridge(lhs.name, rhs.name) && deepEqualsNuxieBridge(lhs.properties, rhs.properties)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PActivityInfo")
    deepHashNuxieBridge(value: schemaVersion, hasher: &hasher)
    deepHashNuxieBridge(value: id, hasher: &hasher)
    deepHashNuxieBridge(value: timestampMs, hasher: &hasher)
    deepHashNuxieBridge(value: receivedAtMs, hasher: &hasher)
    deepHashNuxieBridge(value: name, hasher: &hasher)
    deepHashNuxieBridge(value: properties, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PPurchaseRequest: Hashable {
  var requestId: String? = nil
  var platform: String? = nil
  var productId: String? = nil
  var storeProductId: String? = nil
  var basePlanId: String? = nil
  var purchaseOptionId: String? = nil
  var offerId: String? = nil
  var placementId: String? = nil
  var displayName: String? = nil
  var description: String? = nil
  var productType: String? = nil
  var period: String? = nil
  var periodCount: Int64? = nil
  var introductoryTerms: PIntroductoryTerms? = nil
  var displayPrice: String? = nil
  var eligibilityJws: String? = nil
  var billingPlan: String? = nil
  var timestampMs: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PPurchaseRequest? {
    let requestId: String? = nilOrValue(pigeonVar_list[0])
    let platform: String? = nilOrValue(pigeonVar_list[1])
    let productId: String? = nilOrValue(pigeonVar_list[2])
    let storeProductId: String? = nilOrValue(pigeonVar_list[3])
    let basePlanId: String? = nilOrValue(pigeonVar_list[4])
    let purchaseOptionId: String? = nilOrValue(pigeonVar_list[5])
    let offerId: String? = nilOrValue(pigeonVar_list[6])
    let placementId: String? = nilOrValue(pigeonVar_list[7])
    let displayName: String? = nilOrValue(pigeonVar_list[8])
    let description: String? = nilOrValue(pigeonVar_list[9])
    let productType: String? = nilOrValue(pigeonVar_list[10])
    let period: String? = nilOrValue(pigeonVar_list[11])
    let periodCount: Int64? = nilOrValue(pigeonVar_list[12])
    let introductoryTerms: PIntroductoryTerms? = nilOrValue(pigeonVar_list[13])
    let displayPrice: String? = nilOrValue(pigeonVar_list[14])
    let eligibilityJws: String? = nilOrValue(pigeonVar_list[15])
    let billingPlan: String? = nilOrValue(pigeonVar_list[16])
    let timestampMs: Int64? = nilOrValue(pigeonVar_list[17])

    return PPurchaseRequest(
      requestId: requestId,
      platform: platform,
      productId: productId,
      storeProductId: storeProductId,
      basePlanId: basePlanId,
      purchaseOptionId: purchaseOptionId,
      offerId: offerId,
      placementId: placementId,
      displayName: displayName,
      description: description,
      productType: productType,
      period: period,
      periodCount: periodCount,
      introductoryTerms: introductoryTerms,
      displayPrice: displayPrice,
      eligibilityJws: eligibilityJws,
      billingPlan: billingPlan,
      timestampMs: timestampMs
    )
  }
  func toList() -> [Any?] {
    return [
      requestId,
      platform,
      productId,
      storeProductId,
      basePlanId,
      purchaseOptionId,
      offerId,
      placementId,
      displayName,
      description,
      productType,
      period,
      periodCount,
      introductoryTerms,
      displayPrice,
      eligibilityJws,
      billingPlan,
      timestampMs,
    ]
  }
  static func == (lhs: PPurchaseRequest, rhs: PPurchaseRequest) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsNuxieBridge(lhs.requestId, rhs.requestId) && deepEqualsNuxieBridge(lhs.platform, rhs.platform) && deepEqualsNuxieBridge(lhs.productId, rhs.productId) && deepEqualsNuxieBridge(lhs.storeProductId, rhs.storeProductId) && deepEqualsNuxieBridge(lhs.basePlanId, rhs.basePlanId) && deepEqualsNuxieBridge(lhs.purchaseOptionId, rhs.purchaseOptionId) && deepEqualsNuxieBridge(lhs.offerId, rhs.offerId) && deepEqualsNuxieBridge(lhs.placementId, rhs.placementId) && deepEqualsNuxieBridge(lhs.displayName, rhs.displayName) && deepEqualsNuxieBridge(lhs.description, rhs.description) && deepEqualsNuxieBridge(lhs.productType, rhs.productType) && deepEqualsNuxieBridge(lhs.period, rhs.period) && deepEqualsNuxieBridge(lhs.periodCount, rhs.periodCount) && deepEqualsNuxieBridge(lhs.introductoryTerms, rhs.introductoryTerms) && deepEqualsNuxieBridge(lhs.displayPrice, rhs.displayPrice) && deepEqualsNuxieBridge(lhs.eligibilityJws, rhs.eligibilityJws) && deepEqualsNuxieBridge(lhs.billingPlan, rhs.billingPlan) && deepEqualsNuxieBridge(lhs.timestampMs, rhs.timestampMs)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PPurchaseRequest")
    deepHashNuxieBridge(value: requestId, hasher: &hasher)
    deepHashNuxieBridge(value: platform, hasher: &hasher)
    deepHashNuxieBridge(value: productId, hasher: &hasher)
    deepHashNuxieBridge(value: storeProductId, hasher: &hasher)
    deepHashNuxieBridge(value: basePlanId, hasher: &hasher)
    deepHashNuxieBridge(value: purchaseOptionId, hasher: &hasher)
    deepHashNuxieBridge(value: offerId, hasher: &hasher)
    deepHashNuxieBridge(value: placementId, hasher: &hasher)
    deepHashNuxieBridge(value: displayName, hasher: &hasher)
    deepHashNuxieBridge(value: description, hasher: &hasher)
    deepHashNuxieBridge(value: productType, hasher: &hasher)
    deepHashNuxieBridge(value: period, hasher: &hasher)
    deepHashNuxieBridge(value: periodCount, hasher: &hasher)
    deepHashNuxieBridge(value: introductoryTerms, hasher: &hasher)
    deepHashNuxieBridge(value: displayPrice, hasher: &hasher)
    deepHashNuxieBridge(value: eligibilityJws, hasher: &hasher)
    deepHashNuxieBridge(value: billingPlan, hasher: &hasher)
    deepHashNuxieBridge(value: timestampMs, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PRestoreRequest: Hashable {
  var requestId: String? = nil
  var platform: String? = nil
  var timestampMs: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PRestoreRequest? {
    let requestId: String? = nilOrValue(pigeonVar_list[0])
    let platform: String? = nilOrValue(pigeonVar_list[1])
    let timestampMs: Int64? = nilOrValue(pigeonVar_list[2])

    return PRestoreRequest(
      requestId: requestId,
      platform: platform,
      timestampMs: timestampMs
    )
  }
  func toList() -> [Any?] {
    return [
      requestId,
      platform,
      timestampMs,
    ]
  }
  static func == (lhs: PRestoreRequest, rhs: PRestoreRequest) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsNuxieBridge(lhs.requestId, rhs.requestId) && deepEqualsNuxieBridge(lhs.platform, rhs.platform) && deepEqualsNuxieBridge(lhs.timestampMs, rhs.timestampMs)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PRestoreRequest")
    deepHashNuxieBridge(value: requestId, hasher: &hasher)
    deepHashNuxieBridge(value: platform, hasher: &hasher)
    deepHashNuxieBridge(value: timestampMs, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PPurchaseResult: Hashable {
  var type: String? = nil
  var message: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PPurchaseResult? {
    let type: String? = nilOrValue(pigeonVar_list[0])
    let message: String? = nilOrValue(pigeonVar_list[1])

    return PPurchaseResult(
      type: type,
      message: message
    )
  }
  func toList() -> [Any?] {
    return [
      type,
      message,
    ]
  }
  static func == (lhs: PPurchaseResult, rhs: PPurchaseResult) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsNuxieBridge(lhs.type, rhs.type) && deepEqualsNuxieBridge(lhs.message, rhs.message)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PPurchaseResult")
    deepHashNuxieBridge(value: type, hasher: &hasher)
    deepHashNuxieBridge(value: message, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PRestoreResult: Hashable {
  var type: String? = nil
  var message: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PRestoreResult? {
    let type: String? = nilOrValue(pigeonVar_list[0])
    let message: String? = nilOrValue(pigeonVar_list[1])

    return PRestoreResult(
      type: type,
      message: message
    )
  }
  func toList() -> [Any?] {
    return [
      type,
      message,
    ]
  }
  static func == (lhs: PRestoreResult, rhs: PRestoreResult) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsNuxieBridge(lhs.type, rhs.type) && deepEqualsNuxieBridge(lhs.message, rhs.message)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PRestoreResult")
    deepHashNuxieBridge(value: type, hasher: &hasher)
    deepHashNuxieBridge(value: message, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PIntroductoryTerms: Hashable {
  var price: String? = nil
  var period: String? = nil
  var periodCount: Int64? = nil
  var cycles: Int64? = nil
  var paymentMode: String? = nil
  var displayDuration: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PIntroductoryTerms? {
    let price: String? = nilOrValue(pigeonVar_list[0])
    let period: String? = nilOrValue(pigeonVar_list[1])
    let periodCount: Int64? = nilOrValue(pigeonVar_list[2])
    let cycles: Int64? = nilOrValue(pigeonVar_list[3])
    let paymentMode: String? = nilOrValue(pigeonVar_list[4])
    let displayDuration: String? = nilOrValue(pigeonVar_list[5])

    return PIntroductoryTerms(
      price: price,
      period: period,
      periodCount: periodCount,
      cycles: cycles,
      paymentMode: paymentMode,
      displayDuration: displayDuration
    )
  }
  func toList() -> [Any?] {
    return [
      price,
      period,
      periodCount,
      cycles,
      paymentMode,
      displayDuration,
    ]
  }
  static func == (lhs: PIntroductoryTerms, rhs: PIntroductoryTerms) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsNuxieBridge(lhs.price, rhs.price) && deepEqualsNuxieBridge(lhs.period, rhs.period) && deepEqualsNuxieBridge(lhs.periodCount, rhs.periodCount) && deepEqualsNuxieBridge(lhs.cycles, rhs.cycles) && deepEqualsNuxieBridge(lhs.paymentMode, rhs.paymentMode) && deepEqualsNuxieBridge(lhs.displayDuration, rhs.displayDuration)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PIntroductoryTerms")
    deepHashNuxieBridge(value: price, hasher: &hasher)
    deepHashNuxieBridge(value: period, hasher: &hasher)
    deepHashNuxieBridge(value: periodCount, hasher: &hasher)
    deepHashNuxieBridge(value: cycles, hasher: &hasher)
    deepHashNuxieBridge(value: paymentMode, hasher: &hasher)
    deepHashNuxieBridge(value: displayDuration, hasher: &hasher)
  }
}

private class NuxieBridgePigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return PConfigureRequest.fromList(self.readValue() as! [Any?])
    case 130:
      return PFeatureAccess.fromList(self.readValue() as! [Any?])
    case 131:
      return PFeatureUsageResult.fromList(self.readValue() as! [Any?])
    case 132:
      return PFeatureSnapshot.fromList(self.readValue() as! [Any?])
    case 133:
      return PVersions.fromList(self.readValue() as! [Any?])
    case 134:
      return PExperienceRef.fromList(self.readValue() as! [Any?])
    case 135:
      return PAppAction.fromList(self.readValue() as! [Any?])
    case 136:
      return PActivityInfo.fromList(self.readValue() as! [Any?])
    case 137:
      return PPurchaseRequest.fromList(self.readValue() as! [Any?])
    case 138:
      return PRestoreRequest.fromList(self.readValue() as! [Any?])
    case 139:
      return PPurchaseResult.fromList(self.readValue() as! [Any?])
    case 140:
      return PRestoreResult.fromList(self.readValue() as! [Any?])
    case 141:
      return PIntroductoryTerms.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class NuxieBridgePigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? PConfigureRequest {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? PFeatureAccess {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? PFeatureUsageResult {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? PFeatureSnapshot {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? PVersions {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? PExperienceRef {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? PAppAction {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else if let value = value as? PActivityInfo {
      super.writeByte(136)
      super.writeValue(value.toList())
    } else if let value = value as? PPurchaseRequest {
      super.writeByte(137)
      super.writeValue(value.toList())
    } else if let value = value as? PRestoreRequest {
      super.writeByte(138)
      super.writeValue(value.toList())
    } else if let value = value as? PPurchaseResult {
      super.writeByte(139)
      super.writeValue(value.toList())
    } else if let value = value as? PRestoreResult {
      super.writeByte(140)
      super.writeValue(value.toList())
    } else if let value = value as? PIntroductoryTerms {
      super.writeByte(141)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class NuxieBridgePigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return NuxieBridgePigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return NuxieBridgePigeonCodecWriter(data: data)
  }
}

class NuxieBridgePigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = NuxieBridgePigeonCodec(readerWriter: NuxieBridgePigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol PNuxieHostApi {
  func configure(request: PConfigureRequest, completion: @escaping (Result<PVersions, Error>) -> Void)
  func restorePurchases(completion: @escaping (Result<PRestoreResult, Error>) -> Void)
  func shutdown(completion: @escaping (Result<Void, Error>) -> Void)
  func identify(distinctId: String, userProperties: [String?: Any?]?, userPropertiesSetOnce: [String?: Any?]?, completion: @escaping (Result<Void, Error>) -> Void)
  func reset(keepAnonymousId: Bool, completion: @escaping (Result<Void, Error>) -> Void)
  func getDistinctId(completion: @escaping (Result<String, Error>) -> Void)
  func getAnonymousId(completion: @escaping (Result<String, Error>) -> Void)
  func getIsIdentified(completion: @escaping (Result<Bool, Error>) -> Void)
  func trigger(event: String, properties: [String?: Any?]?) throws
  func dismiss(completion: @escaping (Result<Void, Error>) -> Void)
  func setLocaleIdentifier(localeIdentifier: String?, completion: @escaping (Result<Void, Error>) -> Void)
  func hasFeature(featureId: String, requiredBalance: Double, entityId: String?, policy: String, completion: @escaping (Result<PFeatureAccess, Error>) -> Void)
  func useFeature(featureId: String, amount: Double, entityId: String?, metadata: [String?: Any?]?) throws
  func useFeatureAndWait(featureId: String, amount: Double, entityId: String?, setUsage: Bool, metadata: [String?: Any?]?, completion: @escaping (Result<PFeatureUsageResult, Error>) -> Void)
  func completePurchase(requestId: String, result: PPurchaseResult) throws
  func completeRestore(requestId: String, result: PRestoreResult) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class PNuxieHostApiSetup {
  static var codec: FlutterStandardMessageCodec { NuxieBridgePigeonCodec.shared }
  /// Sets up an instance of `PNuxieHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: PNuxieHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let configureChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.nuxie_flutter_native.PNuxieHostApi.configure\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      configureChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! PConfigureRequest
        api.configure(request: requestArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      configureChannel.setMessageHandler(nil)
    }
    let restorePurchasesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.nuxie_flutter_native.PNuxieHostApi.restorePurchases\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      restorePurchasesChannel.setMessageHandler { _, reply in
        api.restorePurchases { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      restorePurchasesChannel.setMessageHandler(nil)
    }
    let shutdownChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.nuxie_flutter_native.PNuxieHostApi.shutdown\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      shutdownChannel.setMessageHandler { _, reply in
        api.shutdown { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      shutdownChannel.setMessageHandler(nil)
    }
    let identifyChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.nuxie_flutter_native.PNuxieHostApi.identify\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      identifyChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let distinctIdArg = args[0] as! String
        let userPropertiesArg: [String?: Any?]? = nilOrValue(args[1])
        let userPropertiesSetOnceArg: [String?: Any?]? = nilOrValue(args[2])
        api.identify(distinctId: distinctIdArg, userProperties: userPropertiesArg, userPropertiesSetOnce: userPropertiesSetOnceArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      identifyChannel.setMessageHandler(nil)
    }
    let resetChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.nuxie_flutter_native.PNuxieHostApi.reset\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      resetChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let keepAnonymousIdArg = args[0] as! Bool
        api.reset(keepAnonymousId: keepAnonymousIdArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      resetChannel.setMessageHandler(nil)
    }
    let getDistinctIdChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.nuxie_flutter_native.PNuxieHostApi.getDistinctId\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getDistinctIdChannel.setMessageHandler { _, reply in
        api.getDistinctId { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getDistinctIdChannel.setMessageHandler(nil)
    }
    let getAnonymousIdChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.nuxie_flutter_native.PNuxieHostApi.getAnonymousId\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getAnonymousIdChannel.setMessageHandler { _, reply in
        api.getAnonymousId { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getAnonymousIdChannel.setMessageHandler(nil)
    }
    let getIsIdentifiedChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.nuxie_flutter_native.PNuxieHostApi.getIsIdentified\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getIsIdentifiedChannel.setMessageHandler { _, reply in
        api.getIsIdentified { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getIsIdentifiedChannel.setMessageHandler(nil)
    }
    let triggerChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.nuxie_flutter_native.PNuxieHostApi.trigger\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      triggerChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let eventArg = args[0] as! String
        let propertiesArg: [String?: Any?]? = nilOrValue(args[1])
        do {
          try api.trigger(event: eventArg, properties: propertiesArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      triggerChannel.setMessageHandler(nil)
    }
    let dismissChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.nuxie_flutter_native.PNuxieHostApi.dismiss\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      dismissChannel.setMessageHandler { _, reply in
        api.dismiss { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      dismissChannel.setMessageHandler(nil)
    }
    let setLocaleIdentifierChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.nuxie_flutter_native.PNuxieHostApi.setLocaleIdentifier\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setLocaleIdentifierChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let localeIdentifierArg: String? = nilOrValue(args[0])
        api.setLocaleIdentifier(localeIdentifier: localeIdentifierArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      setLocaleIdentifierChannel.setMessageHandler(nil)
    }
    let hasFeatureChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.nuxie_flutter_native.PNuxieHostApi.hasFeature\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      hasFeatureChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let featureIdArg = args[0] as! String
        let requiredBalanceArg = args[1] as! Double
        let entityIdArg: String? = nilOrValue(args[2])
        let policyArg = args[3] as! String
        api.hasFeature(featureId: featureIdArg, requiredBalance: requiredBalanceArg, entityId: entityIdArg, policy: policyArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      hasFeatureChannel.setMessageHandler(nil)
    }
    let useFeatureChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.nuxie_flutter_native.PNuxieHostApi.useFeature\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      useFeatureChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let featureIdArg = args[0] as! String
        let amountArg = args[1] as! Double
        let entityIdArg: String? = nilOrValue(args[2])
        let metadataArg: [String?: Any?]? = nilOrValue(args[3])
        do {
          try api.useFeature(featureId: featureIdArg, amount: amountArg, entityId: entityIdArg, metadata: metadataArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      useFeatureChannel.setMessageHandler(nil)
    }
    let useFeatureAndWaitChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.nuxie_flutter_native.PNuxieHostApi.useFeatureAndWait\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      useFeatureAndWaitChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let featureIdArg = args[0] as! String
        let amountArg = args[1] as! Double
        let entityIdArg: String? = nilOrValue(args[2])
        let setUsageArg = args[3] as! Bool
        let metadataArg: [String?: Any?]? = nilOrValue(args[4])
        api.useFeatureAndWait(featureId: featureIdArg, amount: amountArg, entityId: entityIdArg, setUsage: setUsageArg, metadata: metadataArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      useFeatureAndWaitChannel.setMessageHandler(nil)
    }
    let completePurchaseChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.nuxie_flutter_native.PNuxieHostApi.completePurchase\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      completePurchaseChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestIdArg = args[0] as! String
        let resultArg = args[1] as! PPurchaseResult
        do {
          try api.completePurchase(requestId: requestIdArg, result: resultArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      completePurchaseChannel.setMessageHandler(nil)
    }
    let completeRestoreChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.nuxie_flutter_native.PNuxieHostApi.completeRestore\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      completeRestoreChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestIdArg = args[0] as! String
        let resultArg = args[1] as! PRestoreResult
        do {
          try api.completeRestore(requestId: requestIdArg, result: resultArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      completeRestoreChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol PNuxieFlutterApiProtocol {
  func onFeatureSnapshot(snapshot snapshotArg: PFeatureSnapshot, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onActivity(activity activityArg: PActivityInfo, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onAppAction(action actionArg: PAppAction, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onPurchaseRequest(request requestArg: PPurchaseRequest, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onRestoreRequest(request requestArg: PRestoreRequest, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class PNuxieFlutterApi: PNuxieFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: NuxieBridgePigeonCodec {
    return NuxieBridgePigeonCodec.shared
  }
  func onFeatureSnapshot(snapshot snapshotArg: PFeatureSnapshot, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.nuxie_flutter_native.PNuxieFlutterApi.onFeatureSnapshot\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([snapshotArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onActivity(activity activityArg: PActivityInfo, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.nuxie_flutter_native.PNuxieFlutterApi.onActivity\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([activityArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onAppAction(action actionArg: PAppAction, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.nuxie_flutter_native.PNuxieFlutterApi.onAppAction\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([actionArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onPurchaseRequest(request requestArg: PPurchaseRequest, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.nuxie_flutter_native.PNuxieFlutterApi.onPurchaseRequest\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([requestArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onRestoreRequest(request requestArg: PRestoreRequest, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.nuxie_flutter_native.PNuxieFlutterApi.onRestoreRequest\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([requestArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
